### ISSUE TITLE
Setup basic tests

### ISSUE THREAD

**Issue by kokosing** [prestodb/docker-images#6]
To prevent upload of non-working images it would be nice to setup some basic infra for unit/integration tests which would make sure that images are correct.

**Comment by ArturGajowy** [comment]
Just a reminder we did have some tests run using [bats](https://github.com/sstephenson/bats). I recommend using a version with [this change](https://github.com/sstephenson/bats/pull/200) if you want syntax highlighting in intellij :) HTH :)

**Comment by kokosing** [comment]
Fixed with: https://github.com/prestodb/docker-images/commit/875158d9a381748752075bb6c86dc46b78874c3f
